### ISSUE TITLE
Uncaught TypeError: cal.getCreateDirectories is not a function

### ISSUE THREAD

**Issue by yoshi-gift** [sluedecke/atom-diary#6]
[Enter steps to reproduce:]
1. just do "Atom Diary:ShownProject"

All settings are default.(except for Markdown)

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-diary](https://github.com/sluedecke/atom-diary) package 1.2.0

### Stack Trace

Uncaught TypeError: cal.getCreateDirectories is not a function

```
At /Users/username/.atom/packages/atom-diary/lib/atom-diary.coffee:157

TypeError: cal.getCreateDirectories is not a function
    at Object.showProject (/packages/atom-diary/lib/atom-diary.coffee:157:16)
    at /packages/atom-diary/lib/atom-diary.coffee:44:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:292:20)
    at /app.asar/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:16.8.0 atom-diary:showProject (input.hidden-input)
     -2:02.6.0 settings-view:open (input.hidden-input)
     -1:52.5.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:52 editor:cut-to-end-of-line (input.hidden-input)
     -1:46.3.0 core:confirm (input.hidden-input)
     -1:45.6.0 core:save (input.hidden-input)
     -1:32.1.0 core:close (input.hidden-input)
     -1:31.6.0 command-palette:toggle (input.hidden-input)
     -1:30.8.0 core:backspace (input.hidden-input)
     -1:29.8.0 core:move-down (input.hidden-input)
     -1:29.4.0 core:confirm (input.hidden-input)
     -1:29.4.0 atom-diary:showProject (input.hidden-input)
     -1:27.6.0 settings-view:open (input.hidden-input)
     -1:20.1.0 core:copy (input.hidden-input)
     -0:58.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:58.1.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-diary 1.2.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-runner 2.7.1 
busy-signal 1.3.0 
coffee-navigator 0.0.18 
git-log 0.4.1 
git-plus 7.3.3 
git-time-machine 1.5.9 
go-debug 1.2.0 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
goto-definition 1.3.1 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
language-slim 0.5.0 
linter 2.1.2 
linter-rubocop 1.1.1 
linter-ruby 1.2.5 
linter-ui-default 1.2.2 
markdown-writer 2.6.4 
open-recent 5.0.0 
pretty-json 1.6.3 
project-manager 3.3.4 
rails-open-rspec 1.2.0 
rubocop-auto-correct 1.5.1 
ruby-block 0.3.6 
split-diff 1.3.0 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by sluedecke** [comment]
I am able to reproduce the bug from a fresh install:

1. install atom-diary
1. ~~configure it to use markdown~~ not dependent on markup language chosen
1. invoke Packages -> Diary -> Diary as Project (Atom Diary:ShowProject)

So I found the root cause and will fix it (works on developer account, does not work yet on testing account)

**Comment by yoshi-gift** [comment]
@sluedecke 
thank you for your fix :)
