### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '~/Diary'

### ISSUE THREAD

**Issue by bsahane** [sluedecke/atom-diary#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: "Red Hat
**Thrown From**: [atom-diary](https://github.com/sluedecke/atom-diary) package 1.2.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/home/bsahane/Diary'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, scandir '/home/bsahane/Diary'
    at Object.readdirSync (fs.js:854:3)
    at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
    at Object.createPrintableDiary (/packages/atom-diary/lib/calendar-lib.coffee:55:14)
    at Object.createPrintableDiary (/packages/atom-diary/lib/atom-diary.coffee:107:9)
    at Object.createAndOpenPrintableDiary (/packages/atom-diary/lib/atom-diary.coffee:97:8)
    at /packages/atom-diary/lib/atom-diary.coffee:47:107)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:350690)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:786865)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:794836)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
  3x -2:09.7.0 core:backspace (input.hidden-input)
 13x -1:54.6.0 core:move-left (input.hidden-input)
  8x -1:14.6.0 core:backspace (input.hidden-input)
     -1:10.7.0 core:move-right (input.hidden-input)
  2x -1:09.3.0 core:delete (input.hidden-input)
     -0:26.5.0 atom-diary:toggleCalendar (div.package-detail)
     -0:09.1.0 atom-diary:createAndOpenPrintableDiary (div.package-detail)
```

### Non-Core Packages

```
atom-diary 1.2.1 
markdown-table-editor 1.1.3 
table-editor 0.2.2 
```

**Comment by sluedecke** [comment]
Thanks for your bug report!

Does the folder `/home/bsahane/Diary` actually exist?

**Comment by sluedecke** [comment]
Can you give the version I commited here a try?
